### ISSUE TITLE
Sometimes the patching fails

### ISSUE THREAD

**Issue by gitAdrianK** [gitAdrianK/MoreSaves#20]
`Encountered Exception when trying to call 'Before Level Load' method for mod 'Zebra.MoreSaves': System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: The method or operation is not implemented.
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at MoreSaves.Patching.SaveHelper..ctor(Harmony harmony)
   at MoreSaves.ModEntry.BeforeLevelLoad()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at JumpKing.Mods.ModLoader.CallBeforeLevelLoadMethods()`

this is harmony weirdness, generic methods patching fails, no idea why it happens

**Comment by gitAdrianK** [comment]
if the first mod that uses harmony loads and its v2.3.3 it breaks more saves as it specifically only works with harmony v2.2.2, the reason why specifically the accelerate blocks mod broke stuff for me was that it would be loaded first and uses v2.3.3, while w/o it a mod would load that uses v2.2.2;
